name: test5
description: "新しいFlutterプロジェクト"
# 以下の行は、`flutter pub publish`を使用してパッケージをpub.devに誤って公開することを防ぎます。
# これはプライベートパッケージに推奨される設定です。
publish_to: 'none' # pub.devに公開する場合はこの行を削除してください

# 以下はアプリケーションのバージョンとビルド番号を定義します。
# バージョン番号は1.2.43のように、ドットで区切られた3つの数字で、
# その後に任意でビルド番号を+で続けることができます。
# バージョンとビルド番号は、flutter buildで--build-nameと--build-numberを
# 指定することで上書きできます。
# Androidでは、build-nameはversionNameとして、build-numberはversionCodeとして使用されます。
# Androidのバージョニングについての詳細は以下を参照：
# https://developer.android.com/studio/publish/versioning
# iOSでは、build-nameはCFBundleShortVersionStringとして、build-numberは
# CFBundleVersionとして使用されます。
# iOSのバージョニングについての詳細は以下を参照：
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windowsでは、build-nameは製品とファイルバージョンのメジャー、マイナー、
# パッチ部分として使用され、build-numberはビルドサフィックスとして使用されます。
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# 依存関係は、パッケージが動作するために必要な他のパッケージを指定します。
# パッケージの依存関係を最新バージョンに自動でアップグレードするには、
# `flutter pub upgrade --major-versions`の実行を検討してください。
# または、以下のバージョン番号を手動でpub.devで利用可能な最新バージョンに
# 更新することで依存関係を更新できます。
# 利用可能な新しいバージョンがある依存関係を確認するには、
# `flutter pub outdated`を実行してください。
dependencies:
  flutter:
    sdk: flutter

  # 以下は、iOSスタイルのアイコンのためにCupertino Iconsフォントを
  # アプリケーションに追加します。
  cupertino_icons: ^1.0.8
  mobile_scanner: ^5.2.3
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 以下の"flutter_lints"パッケージには、推奨されるlintルールのセットが含まれており、
  # 良いコーディング習慣を推奨します。パッケージによって提供されるlintセットは、
  # パッケージのルートにある`analysis_options.yaml`ファイルで有効化されています。
  # 特定のlintルールの無効化や追加のルール有効化については、そのファイルを参照してください。
  flutter_lints: ^4.0.0

# このファイルの一般的なDartパートに関する情報については、
# 以下のページを参照してください: https://dart.dev/tools/pub/pubspec

# 以下のセクションはFlutterパッケージに特有のものです。
flutter:
  # 以下の行は、Material Iconsフォントがアプリケーションに含まれることを
  # 保証し、material Iconsクラスでアイコンを使用できるようにします。
  uses-material-design: true

  # アプリケーションにアセットを追加するには、以下のようにassetsセクションを追加します：
  assets:
    - images/